---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.3.0 # renovate: depName=aquaproj/aqua-registry

packages:
  - name: direnv/direnv@v2.32.2
  - name: google/go-jsonnet@v0.20.0
  - name: google/yamlfmt@v0.9.0
  - name: hadolint/hadolint@v2.12.0
  - name: nektos/act@v0.2.45
  - name: peco/peco@v0.5.11
  - name: rhysd/actionlint@v1.6.24
  - name: stedolan/jq@jq-1.6
  - name: x-motemen/ghq@v1.4.2
