---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v2.20.1 # renovate: depName=aquaproj/aqua-registry

packages:
  - name: direnv/direnv@v2.31.0
  - name: peco/peco@v0.5.10
  - name: x-motemen/ghq@v1.3.0
