---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v3.122.0 # renovate: depName=aquaproj/aqua-registry

packages:
  - name: direnv/direnv@v2.32.2
  - name: golang/go@go1.19.5
  - name: golangci/golangci-lint@v1.50.1
  - name: google/go-jsonnet@v0.19.1
  - name: hadolint/hadolint@v2.12.0
  - name: nektos/act@v0.2.35
  - name: peco/peco@v0.5.10
  - name: rhysd/actionlint@v1.6.22
  - name: stedolan/jq@jq-1.6
  - name: x-motemen/ghq@v1.3.0
